"""create_user_table

Revision ID: 81931b0a9912
Revises: 
Create Date: 2019-06-01 18:19:09.911929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81931b0a9912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
